### ISSUE TITLE
Собрать датасет команд, игроков АПЛ 

### ISSUE THREAD

**Issue by Nikita-hub000** [hse-mlds-2023-epl-prediction/annual-project#2]
https://www.sofascore.com - нашел такой сайт, как по мне самый объемный по данным. Можно также дополнить данные вторым заходом ( например пройтись по датам и собрать инфу о погоде в этот день в этом городе )

**Comment by hotspurs** [comment]
Еще вот такой сайт есть - там интересная статистика с разбивкой по игрокам, может нам тоже пригодится - https://fbref.com/en/comps/9/misc/Premier-League-Stats

**Comment by Nikita-hub000** [comment]
UPD по https://www.sofascore.com/
Попробовал распарсить оттуда данные сегодня. Прилетел бан по айпи:) 
Возможно временный, на днях буду чекать и пробовать другие варианты.
С ВПН кстати этот сайт не открывается ( у меня корпоративный на ирландии)
